id: PB7866844
initial_creation_type: ocr
source_metadata:
  volumes:
    45838a6b7e844c3591c23c3bff0dd5a0:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: འབྲེལ་པ་བརྟག་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
